# Dockerfile.web
FROM python:3.10-slim

WORKDIR /app

COPY ./Back/app /app/app
COPY ./Back/requirements.txt /app/
COPY ./Back/.env /app/.env

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Variables de entorno (se recomienda usar archivo .env)
ENV FLASK_APP=app
ENV FLASK_RUN_HOST=0.0.0.0

EXPOSE 5000

CMD ["flask", "run"]
