# version: '3.8'
version: "3.3"

services:
  web:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.web
    container_name: flask-web
    env_file:
      - ../Back/.env
    ports:
      - "5000:5000"
    volumes:
      - /mnt/nfs/files:/mnt/nfs/files
    depends_on:
      - worker

  worker:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.worker
    container_name: flask-worker
    volumes:
      - /mnt/nfs/files:/mnt/nfs/files
    env_file:
      - ../Back/.env
  front:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.front
    container_name: front-app
    ports:
      - "80:80"
