version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.web
    container_name: flask-web
    env_file:
      - ../Back/.env
    ports:
      - "5050:5000"
    volumes:
      - nfs-data:/mnt/nfs/files
    depends_on:
      - worker

  worker:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.worker
    container_name: flask-worker
    volumes:
      - nfs-data:/mnt/nfs/files
    env_file:
      - ../Back/.env

volumes:
  nfs-data:
