version: "3.8"
services:
  front:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.front
    container_name: front-app
    ports:
      - "80:80"
  web:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.web
    container_name: flask-web
    env_file:
      - ../Back/.env
    ports:
      - "5000:5000"
    volumes:
      - /mnt/nfs/files:/mnt/nfs/files
